name: Main workflow

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ steps.yarn.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
